import os
from pathlib import Path

DATASET_PATH = Path("./SNAP-Data")
CENTRALITIES_PATH = Path("./centralities")
ELIST_NAME = "facebook.elist"

BETWEENNESS_NODEFRAC = 0.8

PAGERANK_ALPHA = 0.8
PAGERANK_MAXITER = 128
PAGERANK_TOLERANCE = 1e-9

if not os.path.exists(DATASET_PATH):
    os.mkdir(DATASET_PATH)

if not os.path.exists(CENTRALITIES_PATH):
    os.mkdir(CENTRALITIES_PATH)

CONFIG = {
    'DATASET_PATH': DATASET_PATH,
    'CENTRALITIES_PATH': CENTRALITIES_PATH,
    'ELIST_NAME': ELIST_NAME,
    'BETWEENNESS_NODEFRAC': BETWEENNESS_NODEFRAC,
    'PAGERANK_ALPHA': PAGERANK_ALPHA,
    'PAGERANK_MAXITER': PAGERANK_MAXITER,
    'PAGERANK_TOLERANCE': PAGERANK_TOLERANCE
}
